# Generated by Django 2.2.3 on 2019-07-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20180913_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_topic',
            name='ifAnony',
            field=models.BooleanField(default=False, verbose_name='匿名'),
        ),
    ]
