# Generated by Django 2.2.3 on 2019-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_create_topic_ifanony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_topic',
            name='ifAnony',
            field=models.CharField(choices=[('匿名', '匿名'), ('不匿名', '不匿名')], max_length=50, verbose_name='匿名'),
        ),
    ]
