# Generated by Django 2.2.3 on 2019-07-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user_info',
            name='studentID',
            field=models.CharField(default='', max_length=20, verbose_name='学号'),
        ),
    ]
