# Generated by Django 2.2.2 on 2019-07-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190706_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
